languageCode = "de-de"
title = "Geschichten von draußen …"
description = "Berichte von unseren Touren durch Wildnis, Schnee und Berge."
baseurl = "http://outsidestory.de/"
[permalinks]
tour = "/:year-:title/"
[taxonomies]
category = "categories"