titel: 'Skitour Mont Blanc'
zusammenfassung: 'Im dritten Anlauf ging es im April ohne große Schwierigkeiten mit Zelt und Ski auf den Mont Blanc.'
autor: 'Friedjoff'
datum: '2011-04-23'
teaser: 'fotos/27.jpg'